-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPHHDTSrmrz8eK4P6
VkOMlvEKr2JoxVv0Y3nI4iROJAWgCgYIKoZIzj0DAQehRANCAATYarSaO4+XcA4E
6u9jOBDHBuOCqTQjgPo1jls18zgHtabKlWjAffwGHJTtbKBJ8Q4tmByq7LIZfD8r
T1CCib1Y
-----END PRIVATE KEY-----